#!/usr/bin/env python3
# author: Martin Amengual
# github: UNKNOW
# blog: UNKNOW
# Web: UNKNOW
# youtube: UNKNOW
# License: MIT License
# https://github.com/{github}/thinkdiff/blob/master/LICENSE

# --------------------------
#      Dwap
# --------------------------

from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.common.exceptions import *
from selenium import webdriver

import pickle
import sys
import os
import os.path

path_to_app = os.path.join(os.path.dirname(os.path.realpath(sys.argv[0])), 'framework', 'app')

sys.path.append(path_to_app)

from dwap.utils.utils import *
from dwap.utils.utime import *

try:
    installed_chrome_version = getChromeVersion()

    chrome_options = Options()

    # logo from source http://patorjk.com/software/taag/#p=display&f=Chunky&t=dwap
    print("~                                     ")
    print("~      __                             ")
    print("~  .--|  |.--.--.--.---.-.-----.      ")
    print("~  |  _  ||  |  |  |  _  |  _  |      ")
    print("~  |_____||________|___._|   __|  v1.0")
    print("~                        |__|         ")
    print("~                                     ")

    cmds_program(chrome_options)

    print("~  using chrome v" + installed_chrome_version + ", https://www.dwap.com    ")
    print("~                                     ")

    print("~  CTRL+C  to stop                    ")
    print("~                                     ")

    #chrome_options.add_argument("--headless")
    # chrome_options.add_argument("--window-size=1024x1400")
    chrome_options.add_argument('--user-data-dir=' + os.path.join(dwap_env['origin_path'], 'User_Data'))
    chrome_options.add_argument('--allow-running-insecure-content')

    # download Chrome Webdriver
    # http://chromedriver.chromium.org/downloads
    # put driver executable file in the script directory
    chrome_driver = os.path.join(dwap_env['path_to_modules'], 'chromedriver_' + installed_chrome_version)

    # averiguar como se agrega en firefox
    chrome_options.add_extension(os.path.join(dwap_env['path_to_modules'], 'Ignore-x.zip'))


    caps = DesiredCapabilities.CHROME
    caps['goog:loggingPrefs'] = {'browser': 'ALL'} #https://github.com/SeleniumHQ/selenium/wiki/Logging and https://stackoverflow.com/questions/48313111/python-getting-the-console-log-output-of-a-function-in-selenium?rq=1

    #chrome_options.set_capability('loggingPrefs', capabilities)

    driver = webdriver.Chrome(options=chrome_options, executable_path=chrome_driver, desired_capabilities=caps)

    driver.get("https://web.whatsapp.com")

    script_conf = getConfScript()
    if script_conf is not '':
        driver.execute_script(script_conf)
        timeout(seconds=0, repeat=False, callback=print_consolelog_chrome, args=(driver,))

    print('Runing server.js in chrome!')
    script = getServerScript()
    driver.execute_script(script)
    print('Script executed!')

    t1 = timeout(seconds=0.5, repeat=True, callback=print_consolelog_chrome, args=(driver,))

    #driver.close()
    sys.exit(-1)

except KeyboardInterrupt:
    print('\nProgram stoped...')
    sys.exit(0)
except InvalidArgumentException as e:
    print(e)
    print('Posible solution: close all chrome windows.')
    sys.exit(0)